# Generated by Django 5.0.4 on 2024-05-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_alter_song_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
