# Generated by Django 5.0.4 on 2024-05-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_song_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(max_length=256),
        ),
    ]
