# Generated by Django 5.0.4 on 2024-05-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_alter_song_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.song')),
            ],
        ),
    ]
