# Generated by Django 5.0.4 on 2024-09-12 23:54

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('band', '0007_songpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=256, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('tshirt_size', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='is_active',
            new_name='in_gig_rotation',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songpart',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='band.song'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='songpart',
            order_with_respect_to='song',
        ),
        migrations.CreateModel(
            name='PartAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.instrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.bandmember')),
                ('song_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.songpart')),
            ],
        ),
    ]
