# Generated by Django 5.1.1 on 2025-02-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0012_giginstrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandmember',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.AddConstraint(
            model_name='gigattendance',
            constraint=models.UniqueConstraint(fields=('gig', 'member'), name='unique GigAttendance'),
        ),
        migrations.AddConstraint(
            model_name='giginstrument',
            constraint=models.UniqueConstraint(fields=('gig', 'instrument'), name='unique GigInstrument'),
        ),
        migrations.AddConstraint(
            model_name='partassignment',
            constraint=models.UniqueConstraint(fields=('member', 'song_part', 'instrument'), name='unique PartAssignment'),
        ),
    ]
