# Generated by Django 5.1.1 on 2025-02-12 23:42

import band.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0014_partassignment_performance_readiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigPartAssignmentOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.gig')),
                ('gig_instrument', models.ForeignKey(limit_choices_to=band.models.callable_limit, on_delete=django.db.models.deletion.CASCADE, to='band.giginstrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.bandmember')),
                ('song_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.songpart')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gig', 'member'), name='unique GigPartAssignmentOverride')],
            },
        ),
    ]
