# Generated by Django 5.1.1 on 2025-02-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('band', '0015_gigpartassignmentoverride'), ('band', '0016_remove_gigpartassignmentoverride_unique_gigpartassignmentoverride'), ('band', '0017_remove_gigpartassignmentoverride_gig_and_more'), ('band', '0018_gigpartassignmentoverride_performance_readiness')]

    dependencies = [
        ('band', '0014_partassignment_performance_readiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigPartAssignmentOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.giginstrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.bandmember')),
                ('song_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.songpart')),
                ('performance_readiness', models.CharField(choices=[('ready', 'Ready to Perform'), ('backup', 'Can Perform as Backup')], default='ready', max_length=256)),
            ],
            options={
                'constraints': [],
            },
        ),
    ]
