# Generated by Django 5.1.1 on 2025-02-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0015_gigpartassignmentoverride'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gigpartassignmentoverride',
            name='unique GigPartAssignmentOverride',
        ),
    ]
