# Generated by Django 5.1.1 on 2025-02-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0016_remove_gigpartassignmentoverride_unique_gigpartassignmentoverride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigpartassignmentoverride',
            name='gig',
        ),
        migrations.AlterField(
            model_name='gigpartassignmentoverride',
            name='gig_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.giginstrument'),
        ),
    ]
