# Generated by Django 5.1.1 on 2025-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0017_remove_gigpartassignmentoverride_gig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigpartassignmentoverride',
            name='performance_readiness',
            field=models.CharField(choices=[('ready', 'Ready to Perform'), ('backup', 'Can Perform as Backup')], default='ready', max_length=256),
        ),
    ]
