# Generated by Django 5.1.1 on 2025-02-18 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0015_gigpartassignmentoverride_squashed_0018_gigpartassignmentoverride_performance_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
