# Generated by Django 5.1.1 on 2025-02-23 04:34

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0021_alter_giginstrument_options_gigsetlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
