# Generated by Django 5.1.1 on 2025-02-23 04:42

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0023_alter_gig_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='notes',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
