# Generated by Django 5.1.1 on 2025-03-04 06:05

import djangoyearlessdate.models
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0024_alter_gig_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmember',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='birthday',
            field=djangoyearlessdate.models.YearlessDateField(blank=True, max_length=4, null=True),
        ),
    ]
