# Generated by Django 5.1.1 on 2025-03-17 04:07

import djangoyearlessdate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0025_alter_bandmember_bio_alter_bandmember_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandSpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', djangoyearlessdate.models.YearlessDateField(max_length=4)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='giginstrument',
            name='unique GigInstrument',
        ),
        migrations.AlterField(
            model_name='gigattendance',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maybe_available', 'Maybe Available'), ('unavailable', 'Unavailable')], max_length=256),
        ),
        migrations.AddConstraint(
            model_name='giginstrument',
            constraint=models.UniqueConstraint(fields=('gig', 'instrument'), name='unique GigInstrument', violation_error_message='The instrument is already assigned to this gig.'),
        ),
    ]
