# Generated by Django 5.1.1 on 2025-03-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0026_bandspecialdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='include_in_gig_song_count',
            field=models.BooleanField(default=True),
        ),
    ]
