# Generated by Django 5.1.1 on 2026-08-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0028_gigpartassignmentoverride_override_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_small_group',
            field=models.BooleanField(default=False, help_text='If checked, this gig is excluded from coverage-risk attendance stats.'),
        ),
    ]
