# Generated by Django 5.1.1 on 2026-08-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0029_gig_is_small_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='include_in_coverage_risk',
            field=models.BooleanField(default=True, help_text='If unchecked, assignments on this instrument are ignored by the Coverage Risk report (e.g. Drumset / Engine Room, where any drummer can cover).'),
        ),
    ]
