# Generated by Django 5.1.1 on 2026-08-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0030_instrument_include_in_coverage_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='partassignment',
            name='can_solo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='songpart',
            name='has_solo',
            field=models.BooleanField(default=False),
        ),
    ]
