# Generated by Django 5.1.1 on 2026-08-10 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0031_songpart_has_solo_partassignment_can_solo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_drum_kit_cover_instrument',
            field=models.BooleanField(default=False, help_text='If checked, this instrument is the target for drum-kit cover fallbacks (expect exactly one instrument flagged).'),
        ),
        migrations.CreateModel(
            name='DrumKitCoverPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(help_text='Lower number = preferred cover (e.g. 1 before 2).')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='band.bandmember')),
            ],
            options={
                'ordering': ['priority', 'member__user__first_name', 'member__user__last_name'],
            },
        ),
    ]
