name: Deploy to Elastic Beanstalk (DEV)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y zip

      - name: Install poetry
        run: pipx install "poetry==2.0.1"

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install python Dependencies
        run: poetry install

      - name: Prep static files
        run: poetry run python prsb/manage.py collectstatic --noinput

      - name: Package application
        run: |
          ZIP_FILE="deploy-${{ github.run_id }}.zip"
          zip -r $ZIP_FILE prsb Dockerfile poetry.lock pyproject.toml
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV

      - name: Upload to Elastic Beanstalk
        env:
          APPLICATION_NAME: Phinney Ridge Steel Band Site
          ENVIRONMENT_NAME: prsb-site-dev2
          S3_BUCKET: elasticbeanstalk-us-west-2-905418288995 
        run: |
          aws s3 cp $ZIP_FILE s3://$S3_BUCKET/$ZIP_FILE
          aws elasticbeanstalk create-application-version \
            --application-name "$APPLICATION_NAME" \
            --version-label "deploy-${{ github.run_id }}" \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=$ZIP_FILE
          aws elasticbeanstalk update-environment \
            --application-name "$APPLICATION_NAME"
            --environment-name $ENVIRONMENT_NAME
            --version-label "deploy-${{ github.run_id }}"
